vpc_name             = "my-vpc"
cidr_block           = "10.0.0.0/16"
public_subnet_cidrs  = ["10.0.1.0/24", "10.0.2.0/24"]
availability_zones   = ["us-west-2a", "us-west-2b"]
private_subnet_cidrs = ["10.0.3.0/24", "10.0.4.0/24"]
igw                  = "my-igw"
private_route_cidr   = "0.0.0.0/0"
public_route_cidr    = "0.0.0.0/0"
eip                  = "my-elastic-ip"
nat_gateway          = "my-nat-gateway"
node_role_name       = "NodeIamrole"
cluster_role_name    = "ClusterIamrole"
cluster_name         = "my-eks-cluster"
eks_version          = "1.31"
node_group_name      = "eks-node-group"
instance_types       = ["t2.large"]
desired_size         = 1
max_size             = 3
min_size             = 1